openapi: 3.0.3

info:
  title: Device Configure Management API
  description: |
    API for managing device configuration.
    Intended for use by the web GUI

  version: "1"

  contact:
    name: Mender Support
    email: support@mender.io
    url: https://mender.io/contact-us

  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://hosted.mender.io/api/management/v1/deviceconfig

# Global security definitions
security:
  - ManagementJWT: []

tags:
  - name: ManagementAPI

paths:
  /config/devices/{deviceId}:
    get:
      operationId: Get key-value pair store
      tags:
        - ManagementAPI
      summary: Query the configuration store; retrieve all key-value pairs
      parameters:
        - in: path
          name: deviceId
          schema:
            type: string
          required: true
          description: ID of the device to query.
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  expected:
                    type: array
                    items:
                      $ref: '#/components/schemas/Parameter'
                  actual:
                    type: array
                    items:
                      $ref: '#/components/schemas/Parameter'
                  updated_ts:
                    type: string
                  report_ts:
                    type: string
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Not Found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      operationId: Store a set of key-value pairs
      tags:
        - ManagementAPI
      summary: Set a key-value pair store, updating if existing, removing if empty
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                expected:
                  type: array
                  items:
                    $ref: '#/components/schemas/Parameter'
      parameters:
        - in: path
          name: deviceId
          schema:
            type: string
          required: true
          description: ID of the device to query.
      responses:
        201:
          description: Created
        400:
          description: Bad Request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  securitySchemes:
    ManagementJWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: |
        JWT token issued by 'POST /api/management/v1/useradm/auth/login'

        The JWT can be alternatively passed as a cookie named "JWT".

  schemas:
    Parameter:
      type: object
      properties:
        key:
          type: string
          description: Configuration key.
        value:
          type: string
          description: Configuration value.

    Error:
      type: object
      properties:
        error:
          type: string
          description: Description of the error.
        request_id:
          type: string
          description:
            Request ID passed with the request X-Men-Requestid header
            or generated by the server.
      description: Error descriptor.
      example:
        error: "<error description>"
        request_id: "eed14d55-d996-42cd-8248-e806663810a8"


  responses:
    InternalServerError:
      description: Internal Server Error.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "internal error"
            request_id: "eed14d55-d996-42cd-8248-e806663810a8"

    InvalidRequestError:
      description: Invalid Request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "bad request parameters"
            request_id: "eed14d55-d996-42cd-8248-e806663810a8"

    ForbiddenError:
      description: |
          The user is not permitted to access the resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            error: "Forbidden"
            request_id: "eed14d55-d996-42cd-8248-e806663810a8"
